sudo: true

language: cpp
cache:
  apt: true
  directories:
    - "$HOME/.hunter"

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'g++-5']
      env:
        - _CC=gcc-5
        - _CXX=g++-5

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - _CC=clang-4.0
        - _CXX=clang++-4.0


    - os: osx
      compiler: gcc
      env:
        - _CC=gcc
        - _CXX=g++

    - os: osx
      compiler: clang
      env:
        - _CC=clang
        - _CXX=clang++


script:
  - export CC=$_CC
  - export CXX=$_CXX
  -
  # build and test ed25519
  - mkdir build && cd build
  - cmake .. -DTESTING=ON
  - make -j2 -k
  - ctest
  - sudo make install
  -
  # build and execute example
  - cd ../example/sign-verify
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
  - ./test1
