version: '1.0.{build}'

image: Visual Studio 2017

environment:
  GITHUB_HUNTER_TOKEN:
    secure: 7UxfSeutWTh3NbFTzLMB/ExrKU85qVRkqFf25KM2w07AyoasE4+fVYvQjYqmVK8O
  GITHUB_HUNTER_USERNAME:
    secure: BIEF4/JfDFDWuYJl/J8G2w==

cache:
  - C:\.hunter

platform:
  - x64

configuration:
  - Release
  - Debug

build_script:
  # build and test library
  - cmake -G "Visual Studio 15 2017 Win64" . -DTESTING=ON -DCMAKE_BUILD_TYPE=%CONFIGURATIOIN%
  - cmake --build . --config %CONFIGURATION% -- %MSBUILD_ARGS%
  - cmake --build . --config %CONFIGURATION% --target test
  - cmake --build . --config %CONFIGURATION% --target install

  # build and run example
  - cmake -G "Visual Studio 15 2017 Win64" example/sign-verify -DTESTING=ON -DCMAKE_BUILD_TYPE=%CONFIGURATIOIN%
  - cmake --build example/sign-verify --config %CONFIGURATION%
