version: '1.0.{build}'

image: Visual Studio 2017

environment:
  GITHUB_HUNTER_TOKEN:
    secure: 7UxfSeutWTh3NbFTzLMB/ExrKU85qVRkqFf25KM2w07AyoasE4+fVYvQjYqmVK8O
  GITHUB_HUNTER_USERNAME:
    secure: BIEF4/JfDFDWuYJl/J8G2w==

  # for cache uploading
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6.3"
  PYTHON_ARCH: "64"
  PIP: "C:\\Python36-x64\\Scripts\\pip"

cache:
  - C:\.hunter

platform:
  - x64

configuration:
  - Release

build_script:
  # make python available in PATH, and print its version
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -V
  - pip -V
  - pip install requests gitpython

  # build and test library
  - cmake -G "Visual Studio 15 2017 Win64" . -DTESTING=ON -DCMAKE_BUILD_TYPE=%CONFIGURATIOIN%
  - cmake --build . --config %CONFIGURATION% -- %MSBUILD_ARGS%
  - cmake --build . --config %CONFIGURATION% --target test
  - cmake --build . --config %CONFIGURATION% --target install

  # build and run example
  - cmake -G "Visual Studio 15 2017 Win64" example/sign-verify -DCMAKE_BUILD_TYPE=%CONFIGURATIOIN%
  - cmake --build example/sign-verify --config %CONFIGURATION%
