version: '1.0.{build}'

image: Visual Studio 2017

cache:
  - C:\.hunter

platform:
  - x64

configuration:
  - Release
  - Debug

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" . -DTESTING=ON -DCMAKE_BUILD_TYPE=%CONFIGURATIOIN%

build_script:
  - cmake --build . --config %CONFIGURATION% -- %MSBUILD_ARGS%
